export const CryptocurrencyConsts = {
  CRYPTOCURRENCIES: {
    BTC: 'BTC',
    ETH: 'ETH',
    LSK: 'LSK',
    LTC: 'LTC',
    GAME: 'GAME',
    DASH: 'DASH',
    BCC: 'BCC',
    BTG: 'BTG',
    KZC: 'KZC',
    XIN: 'XIN',
    XRP: 'XRP',
    ZEC: 'ZEC',
    GNT: 'GNT',
    OMG: 'OMG',
    FTO: 'FTO',
    ZRX: 'ZRX',
    PAY: 'PAY',
    BAT: 'BAT',
    REP: 'REP',
    NEU: 'NEU',
    TRX: 'TRX',
    AMLT: 'AMLT',
    EXY: 'EXY',
    BOB: 'BOB',
    LML: 'LML',
    BSV: 'BSV',
    BCP: 'BCP',
    XLM: 'XLM',
    ALG: 'ALG'
  },
  CURRENCIES: {
    PLN: 'PLN',
    EUR: 'EUR',
    USD: 'USD',
    BTC: 'BTC',
    USDC: 'USDC',
    GBP: 'GBP'
  }
}
